Repository GiteaBot/gitea-backporter, pull requests merged in 2023-05, with the labels that each got.

#80 Don't try to update open PRs
  src/github.ts
Labels: size/XS

#79 Make sure PRs that include `## :warning: BREAKING` in their body have the `kind/breaking` label
  README.md
  src/github.ts
  src/labels.ts
  src/webhook.ts
Labels: size/M

#82 Better comment in case of backport failure
  src/backport.ts
Labels: size/XS

#87 Disable udd
  .github/workflows/udd.yml
Labels: size/S
