Repository GiteaBot/gitea-backporter, pull requests merged in 2023-08, with the labels that each got.

#99 Update locking script to add comments for issues updated within the last two weeks
  README.md
  src/lock.ts
Labels: size/S

#100 Refactor locking logic to check the last comment date
  README.md
  src/github.ts
  src/github_test.ts
  src/lock.ts
Labels: size/M

#102 add ability to update PR by adding a label
  README.md
  src/labels.ts
  src/mergeQueue.ts
  src/prActions.ts
  src/webhook.ts
Labels: size/M

#101 Check maintainers can modify before attempting to update
  src/github.ts
Labels: size/XS
